In [ ]:
# Python2DB class
import pymysql


class Python2DB():
    def __init__(self):
        self.WL_DB = pymysql.connect(host='220.90.200.176',
                                     port=3306,
                                     user='multi',
                                     passwd='multi!)@(',
                                     db = 'SocialAnalysis',
                                     charset='utf8')
        self.cursor = self.WL_DB.cursor()
        
    def select(self, table, column):
        sql_qr = """
            SELECT {0} FROM {1}
        """.format(column, table)
        self.cursor.execute(sql_qr)
        return self.cursor.fetchall()

    def insert(self, table, columns, values):
        sql_qr2 = """
            INSERT INTO {0}({1})
            VALUES ({2})
        """.format(table, columns, values)
        self.cursor.execute(sql_qr2)
        self.WL_DB.commit()

    def update(self, table, set_content, where_content):
        sql_qr3 = """
            UPDATE {0}
            SET {1}
            WHERE {2}
        """.format(table, set_content, where_content)
        self.cursor.execute(sql_qr3)
        self.WL_DB.commit()

    def delete(self, table, where_content):
        sql_qr4 = """
            DELETE FROM {0} WHERE {1}
        """.format(table, where_content)
        self.cursor.execute(sql_qr4)
        self.WL_DB.commit()

In [2]:
# 폴더 내 파일을 모두 불러옴(생략가능)
import glob

file_path = "C:\\Users\\ehhah\\Downloads\\멀캠\\플젝\\minions\\insta_data\\3조\\*"
file_list = glob.glob(file_path)
file_list

['C:\\Users\\ehhah\\Downloads\\멀캠\\플젝\\minions\\insta_data\\3조\\FOLLOW_RELATION.json',
 'C:\\Users\\ehhah\\Downloads\\멀캠\\플젝\\minions\\insta_data\\3조\\INSTA_FOLLOW_POST.txt',
 'C:\\Users\\ehhah\\Downloads\\멀캠\\플젝\\minions\\insta_data\\3조\\INSTA_POST_FINAL.txt',
 'C:\\Users\\ehhah\\Downloads\\멀캠\\플젝\\minions\\insta_data\\3조\\INSTA_USERS.txt']

In [3]:
# 파일을 데이터프레임으로 불러옴
import pandas as pd

profile_data = pd.read_csv(file_list[3])
profile_data

,Unnamed: 0,index,hashtag,post_date,crawling_time,insta_id
0,0,0,운동,2020-08-21 13:38:56,2020-08-21 13:37:22,1319299351
1,1,1,운동,2020-08-21 13:38:36,2020-08-21 13:37:22,1458703146
2,2,2,운동,2020-08-21 13:38:35,2020-08-21 13:37:22,36593513387
3,3,3,운동,2020-08-21 13:38:30,2020-08-21 13:37:22,2353695326
4,4,4,운동,2020-08-21 13:38:12,2020-08-21 13:37:22,10229940161
...,...,...,...,...,...,...
81971,81971,135574,movie,2020-08-21 19:00:09,2020-08-21 20:21:10,1690786950
81972,81972,135575,movie,2020-08-21 18:59:18,2020-08-21 20:21:10,38769614076
81973,81973,135576,movie,2020-08-21 18:54:08,2020-08-21 20:21:10,8011539079
81974,81974,135577,movie,2020-08-21 15:55:52,2020-08-21 20:21:10,39992191790
81975,81975,135578,movie,2020-08-21 14:07:01,2020-08-21 20:21:10,8419953219

In [5]:
list(set(profile_data['hashtag']))

['게임',
 '자전거',
 '오오티디룩',
 'movie',
 '오늘뭐입지',
 '카페스타그램',
 '해외여행',
 '커피맛집',
 '롤',
 '미드',
 '유럽여행',
 '댕댕이',
 '여자코디',
 '모바일',
 '여행스타그램',
 '메스타',
 '존맛탱',
 '축구',
 '여행에미치다',
 '산책',
 '일본여행',
 '영드',
 '영화',
 '카페탐방',
 '애옹이',
 '맛스타그램',
 '운동',
 '국내여행',
 '먹방투어',
 '카페추천',
 '폰게임',
 '스팀',
 'netflix',
 '겜스타그램',
 '라이딩',
 '데일리코디',
 '전원카페',
 '메이플스토리',
 '영화추천',
 '동남아여행',
 '옷스타그램',
 '집사',
 '분위기좋은카페',
 '고양이',
 '낚시',
 'lol',
 '먹방',
 '구독',
 '맛집탐방',
 '반려묘',
 '온라인게임',
 '오오티디',
 '인생샷카페',
 '푸드스타그램',
 '유튜버',
 '먹스타그램',
 '반려견',
 '스트릿패션',
 '유튜브',
 '강아지',
 '맛있다',
 '등산',
 '펫스타그램',
 '서핑',
 '감성카페',
 '골프',
 '야구',
 '여행다녀왔습니다',
 '홈카페',
 '맛집그램',
 '냠냠',
 '데일리룩',
 '넷플릭스추천',
 '모바일게임',
 '게임스타그램',
 '게임추천',
 '유디니',
 '남자코디',
 '리그오브레전드',
 '영화스타그램',
 '여행사진',
 '헬스',
 '카페투어',
 '넷플릭스',
 '메스타그램',
 '패션스타그램',
 '사지말고입양하세요',
 '배그']

In [ ]:
import re

db_class = Python2DB()  # 클래스 객체 선언
post_data_list = []  # 데이터 확인을 위한 리스트 선언
id_list = list(set(profile_data['insta_id']))  # 중복 제거 후 inner_id 리스트
len_id_list = len(id_list)

for i in range(len_id_list):  # 데이터프레임의 크기만큼 돌게 설정
    
    inner_id = str(id_list[i])
    hashtag = list(profile_data['hashtag'][profile_data['insta_id'] == id_list[i]])[0]
    interest = ''
    
    if(hashtag == '게임' or hashtag == '롤' or hashtag == '모바일' or hashtag == '메스타' or hashtag == '폰게임' or hashtag == '스팀' 
       or hashtag == '겜스타그램' or hashtag == '메이플스토리' or hashtag == 'lol' or hashtag == '온라인게임' or hashtag == '모바일게임'
       or hashtag == '게임스타그램' or hashtag == '게임추천' or hashtag == '리그오브레전드' or hashtag == '메스타그램' or hashtag == '배그'):
        interest = 'GA' # 게임
    
    if(hashtag == '존맛탱' or hashtag == '맛스타그램' or hashtag == '먹방투어' or hashtag == '먹방' or hashtag == '푸드스타그램' 
       or hashtag == '먹스타그램' or hashtag == '맛있다' or hashtag == '맛집탐방' or hashtag == '맛집그램' or hashtag == '냠냠'):
        interest = 'MJ'  # 맛집
    
    if(hashtag == 'movie' or hashtag == '미드' or hashtag == '영드' or hashtag == '영화' or hashtag == 'netflix' or hashtag == '구독'
       or hashtag == '영화추천' or hashtag == '유튜버' or hashtag == '유튜브' or hashtag == '넷플릭스추천' or hashtag == '영화스타그램' 
       or hashtag == '넷플릭스'):
        interest = 'MW'  # 미디어 감상
    
    if(hashtag == '댕댕이' or hashtag == '애옹이' or hashtag == '집사' or hashtag == '고양이' or hashtag == '반려묘' 
       or hashtag == '반려견' or hashtag == '강아지' or hashtag == '펫스타그램' or hashtag == '사지말고입양하세요'):
        interest = 'PE'  # 반려동물
        
    if(hashtag == '자전거' or hashtag == '축구' or hashtag == '산책' or hashtag == '운동' or hashtag == '라이딩' or hashtag == '낚시'
      or hashtag == '등산' or hashtag == '서핑' or hashtag == '골프' or hashtag == '야구' or hashtag == '헬스'):
        interest = 'SP'  # 스포츠
        
    if(hashtag == '해외여행' or hashtag == '유럽여행' or hashtag == '여행스타그램' or hashtag == '여행에미치다' or hashtag == '일본여행'
       or hashtag == '국내여행' or hashtag == '여행다녀왔습니다' or hashtag == '동남아여행' or hashtag == '유디니' or hashtag == '여행사진'):
        interest = 'TR'  # 여행
        
    if(hashtag == '오오티디룩' or hashtag == '오늘뭐입지' or hashtag == '여자코디' or hashtag == '데일리코디' or hashtag == '옷스타그램' 
       or hashtag == '오오티디' or hashtag == '스트릿패션' or hashtag == '데일리룩' or hashtag == '남자코디' or hashtag == '패션스타그램'):
        interest = 'FA'  # 패션
        
    if(hashtag == '카페스타그램' or hashtag == '커피맛집' or hashtag == '카페탐방' or hashtag == '카페추천' or hashtag == '전원카페' 
       or hashtag == '분위기좋은카페' or hashtag == '인생샷카페' or hashtag == '감성카페' or hashtag == '홈카페' or hashtag == '카페투어'):
        interest = 'CA'  # 카페
    
    post_data_list.append(
        {"inner_id": inner_id,
         "interest": interest
        })
    try:
        db_class.update('INSTA_PROFILE', "interest = '" + interest + "'", "inner_id = '" + inner_id + "'")
    except:
        print("error = " +  "interest = '" + interest + "'" + "\ninner_id = '" + inner_id + "'")
        pass

In [9]:
follow_relation_data = pd.read_json(file_list[0])
follow_relation_data

            insta_id    follow_id           follow_name      follow_fullname
0         4922234371  39306761196            miu_____ng                    y
1         4922234371   3680315716            angler_seo         앵글러 서태공 , 배배
2         4922234371   4514980397     dasolfishing_mart               다솔낚시마트
3         4922234371  10014374186       garminsports_kr  가민 스포츠 코리아
4         4922234371  14010195784            ju__nhyeok        junhyeok Choi
...              ...          ...                   ...                  ...
2006706  26970769219   8722179315   zaigle_zwc.official  ZAIGLE ZWC.official
2006707  26970769219  12743642616             the_zooen               주 은 ❤️
2006708  26970769219   6115485784  mycafelatte_official       나만의 카페, 마이카페라떼
2006709  26970769219   1007601508              iris9199                  한천수
2006710  26970769219   9124019681                kold72                   콜듀

[2006711 rows x 4 columns]

In [13]:
import re

db_class = Python2DB()  # 클래스 객체 선언
post_data_list = []  # 데이터 확인을 위한 리스트 선언
id_list = list(set(follow_relation_data['follow_id']))  # 중복 제거 후 inner_id 리스트
len_id_list = len(id_list)

for i in range(len_id_list):  # 데이터프레임의 크기만큼 돌게 설정
    
    inner_id = str(id_list[i])
    insta_id = list(follow_relation_data['follow_name'][follow_relation_data['follow_id'] == id_list[i]])[0]
    
    post_data_list.append(
        {"inner_id": inner_id,
         "insta_id": insta_id
        })
    try:
        db_class.update('INSTA_PROFILE', "insta_id = '" + insta_id + "'", "inner_id = '" + inner_id + "'")
    except:
        print("error = " +  "insta_id = '" + insta_id + "'" + "\ninner_id = '" + inner_id + "'")
        pass

In [15]:
import re

db_class = Python2DB()  # 클래스 객체 선언
post_data_list = []  # 데이터 확인을 위한 리스트 선언
id_list = list(set(follow_relation_data['follow_id']))  # 중복 제거 후 inner_id 리스트
len_id_list = len(id_list)
EMOJI = re.compile('[\U00010000-\U0010ffff]', flags=re.UNICODE)  # 이모티콘 제거를 위한 EMOJI 변수

for i in range(len_id_list):  # 데이터프레임의 크기만큼 돌게 설정
    
    inner_id = str(id_list[i])
    profile =  EMOJI.sub(r'', list(follow_relation_data['follow_fullname'][follow_relation_data['follow_id'] == id_list[i]])[0]).replace(',', '  ').replace('"', '').replace("'", "")
    
    post_data_list.append(
        {"inner_id": inner_id,
         "profile": profile
        })
    try:
        db_class.update('INSTA_PROFILE', "profile = '" + profile + "'", "inner_id = '" + inner_id + "'")
    except:
        print("error = " +  "profile = '" + profile + "'" + "\ninner_id = '" + inner_id + "'")
        pass

error = profile = '쏘\(//∇//)\'
inner_id = '878789308'
error = profile = '/ㅡ연희(19)_\'
inner_id = '3072518077'
error = profile = ' 알라\'
inner_id = '409234576'
error = profile = '이윤경\ ᴀᴋᴀ.지원맘 \'
inner_id = '15225781476'
error = profile = '강아지 ੯‧̀͡u\'
inner_id = '8559000670'
error = profile = '੯‧̀͡u\'
inner_id = '7013403189'
error = profile = 'tranquille \tʁɑ̃.kil\'
inner_id = '2246801597'
error = profile = '롱보드 원상 /sang won\'
inner_id = '2714471610'
error = profile = '코코 밀크 ੯‧̀͡u\'
inner_id = '34159175180'
error = profile = 'Wienimals \wē-nə-məls\'
inner_id = '2253173259'
error = profile = '੯‧̀͡u\'
inner_id = '40048048611'
error = profile = '\greece-el-duh\'
inner_id = '212939509'
error = profile = '난 련주 ੯‧̀͡u\'
inner_id = '6502320077'
error = profile = '\shə • rēs\'
inner_id = '1309983'
error = profile = '출구없는 #먹통이네 ੯‧̀͡u\'
inner_id = '32454758111'
error = profile = '담이 ੯‧̀͡u\'
inner_id = '8562060913'
error = profile = '/ᐠ｡ꞈ｡ᐟ\ Miaujestad /ᐠ｡ꞈ｡ᐟ\'
inner_id = '10743211174'
error = profile = 'Star_Moon /ᐠ｡‸｡ᐟ\'
inner_id = '39226791604'
error = profile = ':\'
inner_id = '2226786518'
error = profile = '김달콩੯‧̀͡u\'
inner_id = '12823937684'
error = profile = '쿠키 ੯∙̀͡u\'
inner_id = '40617537266'
error = profile = 'sᴜ ᴊᴜɴɢ ੯‧̀͡u\'
inner_id = '1564473489'